# Generated by Django 3.0.4 on 2020-05-29 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('article_desc', models.CharField(max_length=300)),
                ('article_keywords', models.CharField(max_length=1000)),
                ('article_slug', models.SlugField(max_length=200)),
                ('article_img', models.ImageField(upload_to='article_imgs')),
                ('article_date', models.DateField(default=datetime.date.today)),
                ('article_content', models.TextField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=250)),
                ('auther_email', models.EmailField(max_length=254)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_persons_name', models.CharField(max_length=50)),
                ('comments_content', models.CharField(max_length=300)),
                ('comments_persons_email', models.EmailField(max_length=250)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
                ('comments_of_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='article_auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Auther'),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
