# Generated by Django 3.0.4 on 2020-05-29 13:03

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200529_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=ajaximage.fields.AjaxImageField(),
        ),
    ]
