# Generated by Django 3.0.4 on 2020-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=models.ImageField(upload_to='article_imgs'),
        ),
    ]
