# Generated by Django 3.0.4 on 2020-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200530_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_content',
            field=models.TextField(),
        ),
    ]
