# Generated by Django 3.0.4 on 2020-05-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200531_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_of_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Articles'),
        ),
    ]
