# Generated by Django 3.0.4 on 2020-05-31 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200531_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_name', models.CharField(max_length=50)),
                ('messages_email', models.EmailField(max_length=254)),
                ('messages_content', models.TextField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
    ]
