# Generated by Django 3.0.4 on 2020-06-03 20:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
