# Generated by Django 3.0.4 on 2020-06-04 12:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200604_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
