# Generated by Django 3.0.4 on 2020-06-05 20:25

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200604_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
