# Generated by Django 3.0.4 on 2020-06-01 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=250)),
                ('img_file', models.ImageField(upload_to='gallery')),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
    ]
